### ISSUE TITLE
Generated conf.py files in release tarball incompatible with Sphinx 8.x

### ISSUE THREAD

**Issue by jwakely** [uxlfoundation/oneTBB#1576]
# Summary

The `doc/GSG/conf.py` and `doc/main/conf.py` files in the release tarball https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.0.0.tar.gz have the following line:

```python
intersphinx_mapping = {'https://docs.python.org/': None}
```

# Version
2022.0.0

# Environment
Fedora Linux rawhide, with Sphinx 8.1.3

# Observed Behavior
The documentation produces a build error:
https://bugzilla.redhat.com/show_bug.cgi?id=2329903

# Expected Behavior
Builds OK.

I would send a pull request to change it, but those files seem to be generated and I'm not sure how that's done.

For more information, see https://bugzilla.redhat.com/show_bug.cgi?id=2329903 and for a similar fix in another project see https://github.com/jupyterlab/jupyterlab/pull/14423

**Comment by omalyshe** [comment]
@jwakely This was fixed in the release branch as well - https://github.com/uxlfoundation/oneTBB/blob/onetbb_2022/doc/conf.py#L301 
For me the archive at the tag https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.0.0.tar.gz . Please check again.

**Comment by jwakely** [comment]
The [v2022.0.0.tar.gz](https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.0.0.tar.gz) archive has it fixed in `doc/conf.py` but not in the two generated files `doc/GSG/conf.py` and `doc/main/conf.py`:

```
tmp$ mkdir tbb
tmp$ cd tbb
tbb$ wget https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.0.0.tar.gz
v2022.0.0.tar.gz     100% [=========================================================================================================>]    2.53M   32.65MB/s
                          [Files: 1  Bytes: 2.53M [3.71MB/s] Redirects: 1  Todo: 0  Errors: 0                                        ]
tbb$ tar xf v2022.0.0.tar.gz 
tbb$ grep -R  intersphinx_mapping oneTBB-2022.0.0/
oneTBB-2022.0.0/doc/GSG/conf.py:intersphinx_mapping = {'https://docs.python.org/': None}
oneTBB-2022.0.0/doc/conf.py:intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}
oneTBB-2022.0.0/doc/main/conf.py:intersphinx_mapping = {'https://docs.python.org/': None}
```

**Comment by jwakely** [comment]
Ah, maybe they're not generated, they just don't exist on the `master` branch. But they're still wrong on the release branch:

https://github.com/uxlfoundation/oneTBB/blob/0c0ff192a2304e114bc9e6557582dfba101360ff/doc/GSG/conf.py#L294

https://github.com/uxlfoundation/oneTBB/blob/0c0ff192a2304e114bc9e6557582dfba101360ff/doc/main/conf.py#L290

**Comment by omalyshe** [comment]
@jwakely Oh, now I see what you mean. Thank you. Will take a look.

**Comment by omalyshe** [comment]
> @jwakely Oh, now I see what you mean. Thank you. Will take a look.

@jwakely Those files and some others were not supposed to be in the package. It is fixed in the branch and will be fixed in the next release package. Thanks again for reporting it!

**Comment by jwakely** [comment]
Great, thanks!

**Comment by omalyshe** [comment]
@jwakely The issue should be fixed in https://github.com/uxlfoundation/oneTBB/releases/tag/v2022.1.0. Can you please check and close the issue if resolved?
